### ISSUE TITLE
Trolley icon isn't showing

### ISSUE THREAD

**Issue by mainulislamfahim** [minhhung2556/romantic_project_flutter_add_to_cart_button#1]
Obx(() {
                  var con = cartController.stateId.obs;
                  return SizedBox(
                    height: 45.h,
                    width: 180.w,
                    child: AddToCartButton(
                      trolley: !productCarted ? const Padding(
                        padding: EdgeInsets.only(left: 8.0),
                        child: Icon(
                          Icons.shopping_cart_rounded,
                          color: ColorName.white,
                          size: 30,
                        ),
                      ) :  Padding(
                        padding: const EdgeInsets.only(left: 8.0),
                        child: Icon(
                          MdiIcons.cartCheck,
                          color: ColorName.white,
                          size: 30,
                        ),
                      ) ,
                      text: Padding(
                        padding: const EdgeInsets.only(left: 20.0),
                        child: AppTextStyleOverFlow(
                          text: !productCarted ? 'Add to Cart' : 'Carted',
                          fontSize: 14.sp,
                          color: ColorName.white,
                          maxLines: 1,
                        ),
                      ),
                      check: SizedBox(
                        height: 48.h,
                        width: 48.w,
                        child: const Icon(
                          Icons.check,
                          color: Colors.white,
                          size: 24,
                        ),
                      ),
                      borderRadius: BorderRadius.circular(24),
                      backgroundColor: ColorName.primaryColor,
                      onPressed: (AddToCartButtonStateId id) {
                        if (id == AddToCartButtonStateId.idle &&
                            !productCarted) {
                          con.value = AddToCartButtonStateId.loading;
                          cartController
                              .updateStateId(AddToCartButtonStateId.loading);
                          Future.delayed(const Duration(seconds: 2), () {
                            con.value = AddToCartButtonStateId.done;
                            cartController
                                .updateStateId(AddToCartButtonStateId.done);
                            cartController.addToCartlist(productIndex.id!);
                            controller.cartIndex.value =
                                cartController.cartlistItems.length;
                            // print(con.value);
                          });
                        } else if (id == AddToCartButtonStateId.done &&
                            productCarted) {
                          con.value = AddToCartButtonStateId.idle;
                          cartController
                              .updateStateId(AddToCartButtonStateId.idle);
                          //cartController.removeFromCartlist(productIndex.id!);
                          controller.cartIndex.value =
                              cartController.cartlistItems.length;

                          Get.toNamed(Routes.CART);
                        }
                      },
                      stateId: con.value,
                    ),
                  );
                }),
                
                The trolley icon isnt showing if the width increment or decrement then it shows otherwise wont showing the icon

**Comment by minhhung2556** [comment]
Fixed in 1.2.0, thank you for your report.
